#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))#!/bin/bash
echo $PATH((`echo $PATH | grep -o ":/" | wc -l'+ 1))
